### ISSUE TITLE
`contrib` prefix

### ISSUE THREAD

**Issue by arthurvr** [jsdf/grunt-coffee-react#3]
`grunt-contrib-*` is a special naming convention the grunt team uses to mark plugins which they create themselves. From [the guidelines](http://gruntjs.com/creating-plugins#naming-your-task):

> The `grunt-contrib` namespace is reserved for tasks maintained by the Grunt team, please name your task something appropriate that avoids that naming scheme.

So I'd suggest you to rename your task. This has been a reason to blacklist plugins from the `gruntjs.com` site as well.

**Comment by jsdf** [comment]
It is?

**Comment by arthurvr** [comment]
@jsdf You published https://www.npmjs.com/package/grunt-contrib-coffee-react (I know it moved but you have to mark it as deprecated too, using [`npm deprecate`](https://docs.npmjs.com/cli/deprecate))

**Comment by jsdf** [comment]
done

**Comment by arthurvr** [comment]
Thxf
