### ISSUE TITLE
Publish 5.0.0 to npm

### ISSUE THREAD

**Issue by ezekg** [jsdf/grunt-coffee-react#7]
Latest version on npm is [2.4.1](https://www.npmjs.com/package/grunt-coffee-react). Currently having to use the repo directly by commit hash:

```json
"devDependencies": {
  "grunt-coffee-react": "git+https://github.com/jsdf/grunt-coffee-react#f539c3594db4c659ae0522295f6cb08e19cfd963",
},
```

Could you publish the newest version?

**Comment by jsdf** [comment]
I've been on vacation, just published it now.

**Comment by ezekg** [comment]
Awesome, thanks. Hope you had a good vacation!
